const articleConstants = {
  GET_ARTICLES_REQUEST: 'GET_ARTICLES_REQUEST',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',

  GET_ARTICLE_REQUEST: 'GET_ARTICLE_REQUEST',
  GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS',
  GET_ARTICLE_FAILURE: 'GET_ARTICLE_FAILURE',

  POST_ARTICLE_REQUEST: 'POST_ARTICLE_REQUEST',
  POST_ARTICLE_SUCCESS: 'POST_ARTICLE_SUCCESS',
  POST_ARTICLE_FAILURE: 'POST_ARTICLE_FAILURE',

  PUT_ARTICLE_REQUEST: 'PUT_ARTICLE_REQUEST',
  PUT_ARTICLE_SUCCESS: 'PUT_ARTICLE_SUCCESS',
  PUT_ARTICLE_FAILURE: 'PUT_ARTICLE_FAILURE',
}

export default articleConstants;
